name: SurvivalEvent
version: '1.0-SNAPSHOT'
main: wueffi.survivalEvent.SurvivalEvent
api-version: '1.21'
load: STARTUP
authors: [ "Waffle [Wueffi]" ]
description: Plugin for the 1000x1000 Map Survival Event

commands:
  playtime:
    description: Check your own playtime for today.
    usage: /playtime
  check:
    description: Check another player's playtime.
    usage: /check <player>
  start:
    description: Start the survival event.
    usage: /start
  end:
    description: End the survival event and show results.
    usage: /end